import { useEffect, useRef, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import {
  AlertTriangle,
  ChevronLeft,
  ChevronRight,
  Loader2,
  Pencil,
  RefreshCw,
  Sunrise,
} from "lucide-react";

import { MarkdownBody } from "@/components/git/shared/MarkdownBody";
import { projectColorFor } from "@/lib/projectColor";
import { useStandupStore } from "@/stores/useStandupStore";
import { useWorkspaceStore, type WorkspaceTab } from "@/stores/useWorkspaceStore";
import { cardClass } from "@/components/sidebar/sectionChrome";

/**
 * Right-side Standup panel: one ADHD-friendly daily report card per open
 * project, generated by a headless Claude run over git commits and agent
 * sessions since the previous report. The newest saved report auto-loads from
 * disk on open (kept until the next day's replaces it); "Generate" (re)builds
 * on demand, and the schedule row arms the daily in-app timer — a run missed
 * while the app was closed is caught up on the next launch. Cards are shown
 * one at a time in a left/right carousel; the pencil opens the prompt editor.
 */
export function StandupPanel() {
  const tabs = useWorkspaceStore((s) => s.tabs);
  const reports = useStandupStore((s) => s.reports);
  const scheduleEnabled = useStandupStore((s) => s.scheduleEnabled);
  const scheduleTime = useStandupStore((s) => s.scheduleTime);
  const setScheduleEnabled = useStandupStore((s) => s.setScheduleEnabled);
  const setScheduleTime = useStandupStore((s) => s.setScheduleTime);
  const loadLatest = useStandupStore((s) => s.loadLatest);
  const generate = useStandupStore((s) => s.generate);

  const [promptEditorOpen, setPromptEditorOpen] = useState(false);

  // Carousel position; clamped when projects close.
  const [index, setIndex] = useState(0);
  useEffect(() => {
    if (index >= tabs.length) setIndex(Math.max(0, tabs.length - 1));
  }, [tabs.length, index]);

  // Cooldown so one physical swipe (a burst of wheel events) fires once —
  // same pattern as the eagle git-panel switcher.
  const lastFire = useRef(0);
  const goPrev = () => setIndex((i) => (i - 1 + tabs.length) % tabs.length);
  const goNext = () => setIndex((i) => (i + 1) % tabs.length);
  const handleWheel = (e: React.WheelEvent<HTMLDivElement>) => {
    if (tabs.length < 2) return;
    if (Math.abs(e.deltaX) <= Math.abs(e.deltaY) * 2) return;
    e.stopPropagation();
    if (Math.abs(e.deltaX) > 15 && Date.now() - lastFire.current > 250) {
      lastFire.current = Date.now();
      if (e.deltaX > 0) goNext();
      else goPrev();
    }
  };

  // Show the newest report already on disk as soon as the panel opens.
  useEffect(() => {
    for (const tab of tabs) {
      void loadLatest(tab.selectedRepoPath ?? tab.projectPath);
    }
  }, [tabs, loadLatest]);

  const anyGenerating = Object.values(reports).some((r) => r.status === "generating");
  const currentTab: WorkspaceTab | undefined = tabs[Math.min(index, tabs.length - 1)];

  return (
    <div>
      {/* Schedule + generate-all controls */}
      <div className={`${cardClass} mb-2 flex flex-col gap-2`}>
        <label className="flex items-center justify-between gap-2 text-xs text-maestro-text">
          <span className="flex items-center gap-1.5">
            <Sunrise size={13} className="text-maestro-accent" />
            Daily report at
          </span>
          <span className="flex items-center gap-1.5">
            <input
              type="time"
              value={scheduleTime}
              onChange={(e) => setScheduleTime(e.target.value)}
              className="rounded border border-maestro-border bg-maestro-surface px-1.5 py-0.5 text-xs text-maestro-text"
              aria-label="Daily report time"
            />
            <input
              type="checkbox"
              checked={scheduleEnabled}
              onChange={(e) => setScheduleEnabled(e.target.checked)}
              aria-label="Enable daily report schedule"
            />
            <button
              type="button"
              onClick={() => setPromptEditorOpen(true)}
              title="Edit the report prompt"
              aria-label="Edit the report prompt"
              className="rounded p-1 text-maestro-muted transition-colors hover:bg-maestro-surface hover:text-maestro-text"
            >
              <Pencil size={12} />
            </button>
          </span>
        </label>
        <p className="text-[10px] leading-snug text-maestro-muted">
          If the app was closed at report time, it catches up on the next
          launch that day. Each report covers everything since the previous
          one, so Monday picks up the whole weekend.
        </p>
        <button
          type="button"
          disabled={anyGenerating || tabs.length === 0}
          onClick={() => {
            for (const tab of tabs) void generate(tab.selectedRepoPath ?? tab.projectPath);
          }}
          className="flex items-center justify-center gap-1.5 rounded bg-maestro-accent/15 px-2 py-1 text-xs font-medium text-maestro-accent transition-colors hover:bg-maestro-accent/25 disabled:opacity-50"
        >
          <RefreshCw size={12} className={anyGenerating ? "animate-spin" : ""} />
          {anyGenerating ? "Generating…" : "Generate now (all projects)"}
        </button>
      </div>

      {/* Carousel header: prev/next + project name + position dots */}
      {currentTab && (
        <>
          {tabs.length >= 2 && (
            <div
              className="mb-2 flex items-center gap-2 rounded border border-maestro-border bg-maestro-surface px-2 py-1.5"
              onWheel={handleWheel}
            >
              <button
                type="button"
                onClick={goPrev}
                className="rounded p-1 text-maestro-muted hover:bg-maestro-card hover:text-maestro-text"
                aria-label="Previous project report"
              >
                <ChevronLeft size={14} />
              </button>
              <div className="flex min-w-0 flex-1 flex-col items-center gap-1">
                <span
                  className="min-w-0 truncate text-xs font-bold"
                  style={{ color: projectColorFor(currentTab.name) }}
                >
                  {currentTab.name}
                </span>
                <div className="flex gap-1.5">
                  {tabs.map((t, i) => (
                    <button
                      key={t.id}
                      type="button"
                      onClick={() => setIndex(i)}
                      aria-label={`Show report for ${t.name}`}
                      className={`h-1.5 w-1.5 rounded-full ${
                        i === index ? "bg-maestro-accent" : "bg-maestro-muted/40"
                      }`}
                    />
                  ))}
                </div>
              </div>
              <button
                type="button"
                onClick={goNext}
                className="rounded p-1 text-maestro-muted hover:bg-maestro-card hover:text-maestro-text"
                aria-label="Next project report"
              >
                <ChevronRight size={14} />
              </button>
            </div>
          )}
          <StandupCard
            tab={currentTab}
            state={reports[currentTab.selectedRepoPath ?? currentTab.projectPath]}
            onGenerate={() => void generate(currentTab.selectedRepoPath ?? currentTab.projectPath)}
          />
        </>
      )}

      <PromptEditorModal open={promptEditorOpen} onClose={() => setPromptEditorOpen(false)} />
    </div>
  );
}

/** One project's report card (the carousel shows one at a time). */
function StandupCard({
  tab,
  state,
  onGenerate,
}: {
  tab: WorkspaceTab;
  state: ReturnType<typeof useStandupStore.getState>["reports"][string] | undefined;
  onGenerate: () => void;
}) {
  const color = projectColorFor(tab.name);
  return (
    <div className={`${cardClass} mb-2`}>
      <div className="mb-1.5 flex items-center gap-1.5">
        <span className="min-w-0 flex-1 truncate text-xs font-bold" style={{ color }}>
          {tab.name}
        </span>
        {state?.report && (
          <span className="shrink-0 text-[9px] text-maestro-muted">{state.report.date}</span>
        )}
        <button
          type="button"
          disabled={state?.status === "generating"}
          onClick={onGenerate}
          title="Generate report for this project"
          aria-label={`Generate report for ${tab.name}`}
          className="shrink-0 rounded p-1 text-maestro-muted transition-colors hover:bg-maestro-surface hover:text-maestro-accent disabled:opacity-50"
        >
          <RefreshCw size={11} className={state?.status === "generating" ? "animate-spin" : ""} />
        </button>
      </div>

      {state?.status === "generating" && (
        <p className="flex items-center gap-1.5 text-[11px] text-maestro-muted">
          <Loader2 size={11} className="animate-spin" />
          Claude is writing the report…
        </p>
      )}
      {state?.status === "error" && (
        <p className="flex items-start gap-1.5 text-[11px] text-maestro-red">
          <AlertTriangle size={11} className="mt-0.5 shrink-0" />
          <span className="min-w-0 break-words">{state.error}</span>
        </p>
      )}
      {state?.report && state.status !== "generating" && (
        <MarkdownBody content={state.report.markdown} className="text-xs" />
      )}
      {(!state || (state.status === "idle" && !state.report)) && (
        <p className="text-[11px] text-maestro-muted">
          No report yet — hit the refresh button above.
        </p>
      )}
    </div>
  );
}

/**
 * Prompt editor: textarea prefilled with the active template (custom or the
 * backend's built-in default). Saving an unchanged/blank text clears the
 * override so the built-in default keeps applying (and future improvements
 * to it are picked up automatically).
 */
function PromptEditorModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const promptTemplate = useStandupStore((s) => s.promptTemplate);
  const setPromptTemplate = useStandupStore((s) => s.setPromptTemplate);
  const [draft, setDraft] = useState("");
  const [defaultPrompt, setDefaultPrompt] = useState<string | null>(null);

  useEffect(() => {
    if (!open) return;
    let cancelled = false;
    invoke<string>("get_default_standup_prompt")
      .then((d) => {
        if (cancelled) return;
        setDefaultPrompt(d);
        setDraft(promptTemplate ?? d);
      })
      .catch((err) => console.error("Failed to load default standup prompt:", err));
    return () => {
      cancelled = true;
    };
    // promptTemplate is only read when the modal opens — edits go to `draft`.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  if (!open) return null;

  const handleSave = () => {
    const trimmed = draft.trim();
    setPromptTemplate(trimmed === "" || draft === defaultPrompt ? null : draft);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
      <div className="flex max-h-[80vh] w-[560px] max-w-[90vw] flex-col gap-2 rounded-lg border border-maestro-border bg-maestro-card p-4">
        <h2 className="text-sm font-semibold text-maestro-text">Standup report prompt</h2>
        <p className="text-[11px] leading-snug text-maestro-muted">
          This prompt is sent to the headless Claude run together with your
          material. Available placeholders:{" "}
          <code>{"{project}"}</code> <code>{"{date}"}</code> <code>{"{since}"}</code>{" "}
          <code>{"{commits}"}</code> <code>{"{sessions}"}</code> <code>{"{overview}"}</code>.
        </p>
        <textarea
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          spellCheck={false}
          className="min-h-[300px] flex-1 resize-y rounded border border-maestro-border bg-maestro-surface p-2 font-mono text-[11px] leading-snug text-maestro-text outline-none focus:border-maestro-blue"
          aria-label="Standup prompt template"
        />
        <div className="flex items-center justify-between gap-2">
          <button
            type="button"
            onClick={() => defaultPrompt !== null && setDraft(defaultPrompt)}
            disabled={defaultPrompt === null}
            className="rounded px-2 py-1 text-xs text-maestro-muted transition-colors hover:bg-maestro-surface hover:text-maestro-text disabled:opacity-50"
          >
            Reset to default
          </button>
          <span className="flex gap-2">
            <button
              type="button"
              onClick={onClose}
              className="rounded px-3 py-1 text-xs text-maestro-muted transition-colors hover:bg-maestro-surface hover:text-maestro-text"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={handleSave}
              className="rounded bg-maestro-accent/15 px-3 py-1 text-xs font-medium text-maestro-accent transition-colors hover:bg-maestro-accent/25"
            >
              Save
            </button>
          </span>
        </div>
      </div>
    </div>
  );
}
