import { useEffect } from "react";
import { AlertTriangle, Loader2, RefreshCw, Sunrise } from "lucide-react";

import { MarkdownBody } from "@/components/git/shared/MarkdownBody";
import { projectColorFor } from "@/lib/projectColor";
import { useStandupStore } from "@/stores/useStandupStore";
import { useWorkspaceStore } from "@/stores/useWorkspaceStore";
import { cardClass } from "@/components/sidebar/sectionChrome";

/**
 * Right-side Standup panel: one ADHD-friendly daily report card per open
 * project, generated by a headless Claude run over git commits and agent
 * sessions since the previous report. Reports auto-load from disk on open;
 * "Generate" (re)builds them on demand, and the schedule row arms the daily
 * in-app timer (the app must be running at that time).
 */
export function StandupPanel() {
  const tabs = useWorkspaceStore((s) => s.tabs);
  const reports = useStandupStore((s) => s.reports);
  const scheduleEnabled = useStandupStore((s) => s.scheduleEnabled);
  const scheduleTime = useStandupStore((s) => s.scheduleTime);
  const setScheduleEnabled = useStandupStore((s) => s.setScheduleEnabled);
  const setScheduleTime = useStandupStore((s) => s.setScheduleTime);
  const loadToday = useStandupStore((s) => s.loadToday);
  const generate = useStandupStore((s) => s.generate);

  // Show whatever is already on disk for today as soon as the panel opens.
  useEffect(() => {
    for (const tab of tabs) {
      void loadToday(tab.selectedRepoPath ?? tab.projectPath);
    }
  }, [tabs, loadToday]);

  const anyGenerating = Object.values(reports).some((r) => r.status === "generating");

  return (
    <div>
      {/* Schedule + generate-all controls */}
      <div className={`${cardClass} mb-2 flex flex-col gap-2`}>
        <label className="flex items-center justify-between gap-2 text-xs text-maestro-text">
          <span className="flex items-center gap-1.5">
            <Sunrise size={13} className="text-maestro-accent" />
            Daily report at
          </span>
          <span className="flex items-center gap-1.5">
            <input
              type="time"
              value={scheduleTime}
              onChange={(e) => setScheduleTime(e.target.value)}
              className="rounded border border-maestro-border bg-maestro-surface px-1.5 py-0.5 text-xs text-maestro-text"
              aria-label="Daily report time"
            />
            <input
              type="checkbox"
              checked={scheduleEnabled}
              onChange={(e) => setScheduleEnabled(e.target.checked)}
              aria-label="Enable daily report schedule"
            />
          </span>
        </label>
        <p className="text-[10px] leading-snug text-maestro-muted">
          Runs while the app is open. Each report covers everything since the
          previous one, so Monday picks up the whole weekend.
        </p>
        <button
          type="button"
          disabled={anyGenerating || tabs.length === 0}
          onClick={() => {
            for (const tab of tabs) void generate(tab.selectedRepoPath ?? tab.projectPath);
          }}
          className="flex items-center justify-center gap-1.5 rounded bg-maestro-accent/15 px-2 py-1 text-xs font-medium text-maestro-accent transition-colors hover:bg-maestro-accent/25 disabled:opacity-50"
        >
          <RefreshCw size={12} className={anyGenerating ? "animate-spin" : ""} />
          {anyGenerating ? "Generating…" : "Generate now (all projects)"}
        </button>
      </div>

      {/* One report card per open project */}
      {tabs.map((tab) => {
        const repoPath = tab.selectedRepoPath ?? tab.projectPath;
        const state = reports[repoPath];
        const color = projectColorFor(tab.name);
        return (
          <div key={tab.id} className={`${cardClass} mb-2`}>
            <div className="mb-1.5 flex items-center gap-1.5">
              <span className="min-w-0 flex-1 truncate text-xs font-bold" style={{ color }}>
                {tab.name}
              </span>
              {state?.report && (
                <span className="shrink-0 text-[9px] text-maestro-muted">{state.report.date}</span>
              )}
              <button
                type="button"
                disabled={state?.status === "generating"}
                onClick={() => void generate(repoPath)}
                title="Generate report for this project"
                aria-label={`Generate report for ${tab.name}`}
                className="shrink-0 rounded p-1 text-maestro-muted transition-colors hover:bg-maestro-surface hover:text-maestro-accent disabled:opacity-50"
              >
                <RefreshCw size={11} className={state?.status === "generating" ? "animate-spin" : ""} />
              </button>
            </div>

            {state?.status === "generating" && (
              <p className="flex items-center gap-1.5 text-[11px] text-maestro-muted">
                <Loader2 size={11} className="animate-spin" />
                Claude is writing the report…
              </p>
            )}
            {state?.status === "error" && (
              <p className="flex items-start gap-1.5 text-[11px] text-maestro-red">
                <AlertTriangle size={11} className="mt-0.5 shrink-0" />
                <span className="min-w-0 break-words">{state.error}</span>
              </p>
            )}
            {state?.report && state.status !== "generating" && (
              <MarkdownBody content={state.report.markdown} className="text-xs" />
            )}
            {(!state || (state.status === "idle" && !state.report)) && (
              <p className="text-[11px] text-maestro-muted">
                No report for today yet — hit the refresh button above.
              </p>
            )}
          </div>
        );
      })}
    </div>
  );
}
